### ISSUE TITLE
Codebase cleanup and consolidation

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1047]
# 1 C++ library structure

## 1.1 Extract kernels from transform and transform_in_place calls

- [x] Continue to rollout changes as in #513.

## 1.2 `variable.h`

`variable.h` contains the variable classes as well as free functions for variables. Addition of new free function thus causes recompilation of everything depending on `variable.h`, even if the dependence is only with the classes, not the functions.

- [x] Move content to two separate header files. `variable.h` may or may not be preserved as a header combining both header for convenience, but probably this is not necessary. See #1051.

## 1.3 Splitting `scipp-core` and `scipp-core-test`

`scipp-core` contains 3 layers that are (or could be made) independent:
- Functionality "below" the `Variable` level, including "element" kernels used in `transform`.
- Functionality at the `Variable` level.
- Functionality above the `Variable` level, i.e., involving `DataArray` and `Dataset`.

For improved modularity when building the library or tests (improving times from modifiying (test) code to being able to run tests) this should be relfected in the C++ library structure.
 - [x] Split `scipp-dataset` from `scipp-core`. See #1054.
 - [x] Split `scipp-variable` from `scipp-core`. See #1068.

# 2 Module and namespace structure

## 2.1 Python

- Should we have `scipp.event`? This would (currently) contain `scipp.event.filter` and `scipp.event.map`. `realign` also supports event data, but it cannot be part of this module since realignment may cover normal data as well. Is it beneficial to have the `scipp.event` module? -> No.

## 2.2 C++

- [ ] Namespaces with `scipp::core`, `scipp::variable`, and `scipp::dataset` are inconsistent. Figure out what we have, and decide on a better structure. When do we use `detail`? Where should `except` be defined?
- [x] ~`scipp::core` mostly becomes `scipp` on the Python side. Not a problem, but maybe confusing?~ Now we have three submodules on the C++ side, which put symbols into `scipp`, so this is consistent.
- [x] Should we lift `Variable`, `DataArray`, and `Dataset` to the `scipp` namespace? This avoids use of `using namespace scipp::core` in many places (tests). Basically we would have:
  ```cpp
  namespace scipp {
  namespace core {
  class Variable;
  Variable sqrt(const VariableConstView &var);
  } // namespace core
  using core::Variable;
  } // namespace scipp

  // in mytest.cpp
  using namespace scipp;
  Variable var;
  sqrt(var); // found via ADL
  ```
     -> Yes, necessary for split of `scipp-core`.

# 3 Other

- [ ] Systematically review and clean up existing code. -> See issue TODO.
     - [ ] Naming of C++ tests files and test fixture names.
- [x] Adding a new `dtype` requires touching quite a few places. Can it be made more convenient?
     - Got marginally improved by removing need for defining "known" dtypes in #1063, but more to do.
     - Significant improvement in #1073.
- [x]  clean-up python  tests that are disabled or commented out #914, but there are others such as `test_datasetslice.py`. (Owen)
- [ ] `mantid.py` has gotten too large and needs to be split up. See also #954. See also Neils comments in #1069 (Owen)
- [x] Remove support for variances for interger dtype? This eats some compilation time and increases package sizes. Is it relevant in practice? It is simple to add this in at a later time.
- [x] Should `scipp::units::m` and similar be of class `units::Unit` instead of a `boost::units::quantity`? Currently we have to be very verbose in many places, e.g., `units::Unit(units::m)` is required in many places that expect a `units::Unit`. Is there a better way, making conversions work better? -> Yes. @SimonHeybrock 
- [ ] Should exceptions be defined near the relevant object instead of `except.h`? -> No, keep.
- [x] Remove `sparseValues` and `sparseVariances` in favor of using, e.g., `values<event_list<double>>`. @nvaytet 
- [x] Replace uses of "sparse" with "event(s)", in particular `sparse_container` should use the new name `event_list` everywhere. -> @nvaytet 
- [x] ~Remove `hasData()` in favor of returning invalid `DataArrayView` from `data()` method, similar to how `None` is returned in Python, and how `unaligned()` works.~ (aborted attempt, since this got more messy than expected with little benefit) @SimonHeybrock 
- [ ] Run all benchmarks before & after #1001, find any significant differences.
- [ ] Figure out what ~~`is_events`~~ `contains_events` should do, and add unit tests. ~Right now it is behaving differently in Python and C++,~ and it is not clear what is most useful for the user/developer.
- [x] Tidy up Python bindings (e.g. move free functions in `Variable.cpp` to a separate file) -> @nvaytet 
- [ ] Replace uses of `setCoord`, `setAttr`, and `setMask` with `coords().set(...)` (etc.). This is more consistent with the DataArray API and Pythin API. Note that the setters directly on dataset *cannot* be removed since the are used to implement things like `coords().set(...)`.
- [ ] Change the remaining camel case `functionName` to `function_name` to be uniform across the board

# 4 Things to document in developer docs

- [x] How to use `transform` and how to write tests for functionality created with it.
- [ ] Differences between C++ and Python implementations (example: `class Dimensions` vs. independent `shape` and `dims`)
- [x] Implementation and logic behind `Variable`, `VariableConcept`, `VariableView` and related classes.

**Comment by OwenArnold** [comment]
Regarding `1.2` and possibly more generally in scipp - can we better follow a layout that allows a better reflection between physical files and logical constructs? You mention splitting variable.h up into two, I think more would be appropriate to aid navigation (and reduce incremental compile times).  As an example, `dataset.h` currently contains the declaration for `DataArray`,  `DatasetConstView` and a number of other classes. I'm proposing that these could be split out better, say for DataArray `data_array.h` (there is already a matching implementation file..`

What I'm proposing above follows with `Large Scale C++ Software Design`, some relevant info here https://github.com/bloomberg/bde/wiki/physical-code-organization

**Comment by SimonHeybrock** [comment]
Agree, but if we follow the link you mention, https://github.com/bloomberg/bde/wiki/physical-code-organization#components states that classes are not components, and explicitly forbids cyclic dependencies. So having `dataset.h` also contain `DataArray` may be in line with what they recommend.

**Comment by OwenArnold** [comment]
> Agree, but if we follow the link you mention, https://github.com/bloomberg/bde/wiki/physical-code-organization#components states that classes are not components, and explicitly forbids cyclic dependencies. So having `dataset.h` also contain `DataArray` may be in line with what they recommend.

Good point, I hadn't considered the cyclic dependency in that example.

**Comment by nvaytet** [comment]
Do we also want to cleanup the python bindings files? For instance, the `variable.cpp` is getting quite large, with templated functions are the top, some variable bindings in the middle, and free functions at the bottom. Maybe this should be split and put templated functions in a header file?

**Comment by SimonHeybrock** [comment]
@nvaytet Good idea! I am also still looking for a better way to write docstrings for overloaded functions to avoid the "Overloaded function" in https://scipp.github.io/python-reference/api.html#free-functions, which is not really useful.

**Comment by SimonHeybrock** [comment]
Closing since likely too old to be useful.
