### ISSUE TITLE
Cleanup phase 1 tasks

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1164]
Overview of remaining tasks for current cleanup phase. If you start working on something, edit your name into the list item. If there is an issue, assign it to yourself.

- [ ] Any remaining bug in 0.4, see https://github.com/scipp/scipp/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A0.4
- [x] @SimonHeybrock Incomplete HTML output #1150. See #1193.
- [x] @rozyczko More useful exception message #1130. See #1181.
- [x] Convention breaking names of coords #1042. See #1179.
- [x] @SimonHeybrock (#1168) As part of #513 we have moved most cases where `transform`, `transform_in_place`, or `accumulate_in_place` are used to have their kernels placed in and tested in `scipp::core::element`.
  - Find relevant cases where this is not done yet and move.
  - Add unit tests. Note that there are a few examples where the operators are already in `element/`, but unit tests do not exist on this level.
  - If it turns out that there are too many, open an issue (for particular cases) and add item here.
- [x] @SimonHeybrock Remove google benchmarks from conda packages #1057. See #1174.
- [x] @SimonHeybrock Cleanup filenames in `dataset/`, extract free functions from `dataset.h` (same as done in `variable/`).
