### ISSUE TITLE
Rethinking event data

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1281]
### 1.1 API UX problems

1. The [API for creating event workspaces](https://scipp.github.io/event-data/overview.html) is not very natural. In principle this would be used little in practice since event data would just be read from a file.
2. Requires a new `dtype` for every type of event list, e.g., `sc.dtype.event_list_float64`, `sc.dtype.event_list_int32`.
3. Coords and data of event lists are separate. Slicing a data array down to a single bin will *not* provide access to an event list as a simple data array view --- it is a data array containing lists.
4. [Realignment mechanism](https://scipp.github.io/user-guide/unaligned-data.html) seems to work, but also feels potentially complicated and non-trivial to understand.
5. Realignment mechanism appears to limited when attempting to support the equivalent to Mantid's `MDEventWorkspace`. The API is in principle available, but without an optimization such as the recursive bucketing used by `MDEventWorkspace` slicing and other lookup will be too slow in practice since in the current implementation it involves a full filter operation on a large event list.
6. Realignment mechanism did not naturally offer the expected benefits when it comes to unit conversion: The idea was to avoid the need of converting a 1D coord into a 2D coord by simply having realigning bin edges that could be kept 1D. In practice, the conversion would still create a 2D coord (which fails, because we do not support realignment with a 2D coord), and a [special `realign` option](https://scipp.github.io/generated/scipp.neutron.convert.html#scipp.neutron.convert) had to be added.
7. No mechanism to prevent length-mismatch between, e.g., event weights and event coords.

### 1.2 Other problems

1. For I/O purposes, storing variable-length data is likely inefficient. Copy into contiguous chunk of memory would be a solution, but comes with extra complexity and copy overhead.
2. Hypothetical overhead from copying many small allocated regions instead of a single contiguous chunk. We have not seen large effects of this in practice yet, but may a closer look would be useful.
3. `sc.realign` comes internally in two flavors, one for event data, one for dense data. There are limitations in the implementation, such as not supporting multi-dimensional histogramming for event data yet.

## 2 Wishes for a better solution

1. `array['spectrum', 17].value` should return a dense `DataArrayView` depending on a single dimension such as `'event'`.
2. Underlying data strored in a single large chunk of memory instead of using "lists of lists".
3. Traditional bucketing as used for TOF event lists of raw data to use a mechanism that can also solve the `MDEventWorkspace` lookup/filter performance problem. In particular the current slicing of buckets (`array['spectrum', 17]`) should be combinable with a more precise selection:
   ```python
   # bucket edges
   qx = array.coords['Qx']
   # qx is Variable(dims=['Qx'], shape=[100], dtype=float64)

   # event Qx
   qx = array['Qx', 4]['Qy', 5]['Qz',6].value.coords['Qx']
   # qx is Variable(dims=['event'], shape=[2342], dtype=float32)
   # note how value in bucket has independent coord
   ```
4. Realignment mechanism made redundant?

## 3 Possible solution

There may be a surprisingly simple solution based on a specialization of [`DataModel`](https://scipp.github.io/developer/variable_implementation.html):
```cpp
template <>
class DataModel<event_list> {
  element_array<pair<index, index>> m_buckets; // list of slice begin/end
  Dim m_dim; // dim to slice
  DataArray m_events;
};
```

While there are *a lot* of unclear details and a number of technical implementation challenges (see below), we can consider how this solves problems and implements wishes discussed above.

- 2.2 (and thus 1.2.1 and 1.2.2) solved by contiguous `m_events`.
- 1.1.2 replaced by a single new `sc.dtype.event_list` (better, more general name may be needed)
- 2.1 solved since we can return a slice of `m_events`.
- 2.3 should just work, since `m_dim` in the `DataModel` specialization is independent of the dims of the underlying `VariableConcept`, i.e., buckets can form a grid of arbitrary shape.
- 1.1.3 solved since an event list would just be a `DataArray`. Access to an event list within a data array would be via `DataArrayView`, i.e., without option to modify size.
- As a surprising side-benefit, this might solve 80% of #1211, by providing a slicable variable that contains a single underlying data array. As a corollary, we should also support `Dataset` here, e.g., by actually specializing as `template <class T> class DataModel<bucket<T>>` where `T` could be `DataArray` or `Dataset`.
- 1.2.3 may be solved, since bucketing is not specific to event data. Can accept and afford reordering/sorting data? Probably sufficient to reorder buckets in case of realigning, e.g., both events and positions. Mechanism simpler since just nested variable.
- 1.1.6 is *not* solved in general. However, the bucket mechanism gives us at least the option to naturally add and subtract event data, without the need to add bin edges for the TOF dimension. That is, we may be able to reduce the number of cases where we run into trouble with 2d coords from unit conversion. For a full solution we would need some  sort of support for dynamic buckets (see inconclusive discussion below).
- 1.1.7 solved naturally by `DataArray` shape checks.

### Limitations

1. Resizing individual event lists not readily possible without "list of lists" data structure. In practice resizing occurs relatively little. If it turns out to be more common that though, we *could* implement an over-allocation mechanism similar to what `std::vector` provides: `m_events` should contain padding between buckets, so individual buckets could be grown until hitting the following bucket, at which point reallacation would become necessary. It is unclear whether this is technically feasible though, since it would not provide multi-threaded size-modifying access to different buckets (unlike the current solution).
2. The current realignment mechanism maps coords of the realigned wrapper into the unaligned data. For example, considering the equivalent of Mantid's `EventWorkspace`, a position coord would be mapped from the realigned wrapper (with TOF dimension and edges) into the unaligned array containing TOF event lists, since the position (spectrum) dimension is not affected by the realignment. It does not appear feasible to do something equivalent in the proposed solution, at least not without adding specialized code to `DataArrayView::value()`.

### Open conceptual questions

- We may want to have a variable containing event list with dimensions not present in the bucketing.
  - For example, we may want to overlay a 1000x1000x1000 X-Y-Z grid to data depending on a single position dimension. Creating this many buckets comes with substantial overhead and may even exceed available memory.
  - Another example would be TOF event lists where we may want to add a pulse-time dimension, e.g., for [sample-environment-parameter filtering ](https://scipp.github.io/event-data/filtering.html) and [arithmetic operations with event data](https://scipp.github.io/event-data/overview.html#Arithmetic-operations). The current realignment mechanism supports this without the need of actual sorting/bucketing and does this on-the-fly instead.
  - Maybe most relevant and critical example: TOF event data for a large powder diffractometer. May have more than `1 Mpixel` and more than `1 kbin` required for normalization to monitor. [Arithmetic support between event data and histograms](https://scipp.github.io/event-data/overview.html#Arithmetic-operations) relies on matching binning for event data on realigned wrapper. If we want to carry over this (desirable) requirement we either have to deal with a excessively large number of buckets, or have a way to avoid buckets while still having the related dimension/shape as part of the variable.
  - Should this only be supported using an explicit syntax, i.e., a dedicated function instead of an operator? Should we keep handling it as a special case of `*` for data arrays, even when not "realigned"?

### Open technical implementation problems

- How should low-level access work, in particular for `transform` implementation. Current mechanism of returning vectors from kernels which are then moved into output event lists would not work. Naive implementation would require a copy, so a better approach is needed.
  - Note that in principle it would be sufficient to provide basic operators between POD types and `DataArray` so `transform` would apply kernels to, e.g., `(DataArrayView, double)`. However, this implementation would also be very inefficient (investigation required on how inefficient).
  - More likely, we may need to reconsider [`VariableConceptT<T>`](https://scipp.github.io/developer/variable_implementation.html) to support a third subclass in addition to `DataModel<T>` and `ViewModel<T>`. The latter is a strided view, whereas the new `DataModel` specialization would require and indexed view. We may thus have `DataModel<T>`, `StrideViewModel<T>`, and `IndexViewModel<T>`. This may actually provide additional benefits at no extra cost, see also #454. For example, it could be used to implement value-based slicing with 2D "ragged" coordinates.
  - After closer consideration, it appears that `ViewModel` is entirely unnecessary and we can implement `VariableView` to instead create an `ElementArrayView` on the fly. This would simplify the overall class structure and avoid memory allocation in `VariableView` (when slicing). This improvement is independent of the other changes discussed here and could be done as a preparation step.
  - For accessing element of event lists, we would either need an alternative to `ElementArrayView` (and the underlying `ViewIndex`) that can be used in transform explicitly (similar to old distinction between `span` and `ElementArrayView` between `Variable` and `VariableView`), or, more desirably, adapt `ElementArrayView` to be able to deal with indices obtained from subspans. The latter is possible and certainly more desirable since it could significantly reduce the amount of instantiations required by `transform`. However, iteration of `ElementArrayView` lies at the core of all `tranform`-based functionality and is directly responsible for the performance of most scipp functions. It will need to be tested if a generalized implementation can yield equivalent performance.
- Current module split may not work any more: Need `DataArray` for instantiating, e.g., `operator*(Variable, Variable)`, where one of the variables contains event lists.
  - Iteration of elements can be based on `ElementArrayView` (or similar new views) and is thus generic.
  - Creating output variable with buckets of `DataArray` may be solvable with some part of dynamic factory / copy construction mechanism.
  - Not clear how to handle `+` and `-` between event data, this cannot really be done without including/linking to `DataArray`.
- `Variable::values<T>` returns a `span<T>` (or `ElementArrayView<T>` for `VariableView::values<T>`). We cannot use either of these, since the proposed specialization of `DataModel` does not actually contain a range of `DataArrayView`. Rather, we would need to generate these on-the-fly. This may require specializations of methods of `Variable` and related classes.
  - Note that there are two cases here, access to the nested elements, i.e., individual events, which might be handled using a generalized `ElementArrayView`. To access the "event lists" we would indeed need on-the-fly generation.

## Subtasks

- [x] Support + and - (or equivalent named functions) with buckets (replacing what is supported for realigned data). See #1331.
- [x] Support * and / (or equivalent named functions) between buckets and histograms (replacing what is supported for realigned data). See #1337.
- [x] Support histogramming. See #1334.
- [ ] Support "event filtering" (replacing what is supported for realigned data).
- [x] Support neutron::convert (replacing what is supported for realigned data). See #1341.
- [x] Refactor "realign" docs into "bucket" docs.
- [ ] Improve performance issues introduced in these refactoring steps. We may need to add special case handling in transform, e.g., for stride 1, so the compiler can generate better code. It is currently unclear whether this is an issue in practice. There is a really significant slowdown in the single-threaded case, but we may still be good enough when using threads to be memory-bandwidth limited.
- [x] Remove `event_list`
- [x] Remove `realign`. See #1337.
- [x] Add `to_buckets` that accepts a dict of bin edges instead of indices. This would then sort the buffer (recursively) and determine indices. Similarely, splitting existing buckets by setting new bin edges (for existing or new dims) should be supportable in the same code.
- [x] Replacements for `flatten()` and `groupby.flatten()`, concatenating all buckets along a dimension. Note that we could now in principle do this in-place without reallocating memory, but in practice an in-place reordering of buckets may be too complex.
- [x] All refactor tests and docs.

**Comment by SimonHeybrock** [comment]
Implementation steps:
1. Generalize `ViewIndex` and benchmark `transform` to see if dense performance affected.
2. Remove `ViewModel` and simplify `Variable` implementation.
3. Specialize `DataModel`.
4. Benchmark `transform` with variables holding specialized `DataModel`.
5. Figure out remaining transform issues and decide on how to move forward.
