### ISSUE TITLE
Umbrella: Implementation details to consider for refactor

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1440]
- [x] `DataArray` is implemented as a single-item `Dataset`. After recent simplications, consider implementing it directly. (will be done in ownership rewrite)
- [ ] `MultiIndex` is too complicated to understand. Does not support seeking to bin elements (seek is only bin-based, which limits threading and load balance).
- [x] `Unit` has hard-coded list of supported units, which limiting.
- [ ] Use of `Eigen` for vectors and matrices.
