### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#1958]
In principle making a release is trivial: Create a release with an `X.Y.Z` tag in GitHub. This triggers the release pipeline, publishes conda packages and docs. In practice however, there are a number of extra tasks that have and are accumulating. This is not sustainable in the long run, and we have to strive for more automation.

Here is a list. Note that the goal is *not* to create a TODO list that we have to run through with every release. Instead, these are things that should be considered for automation. Emphasis is on considered, i.e., automation may not make sense for all:

- [x] Follow proceedure described in https://github.com/scipp/scipp/blob/57b0b11bfdf4d601fc649cd08d72dee5a9b62d07/docs/about/README.md to create and link to "What's New" pages. Fixed in #1959
- [ ] Add links to new version in version selection dropdown menu, see also #1955.
- [ ] Add new section in release notes.
- [x] Add mention of release on front-page in News section. Fixed in #1959
- [ ] Test that `scipp.yml` installs new packages, can be imported, and that version is as expected (matches the tag).

Downstream, e.g. `scippneutron`:
- [ ] Pretty much the same as above
- [ ] Update required scipp version in `CMakeLists.txt`
- [ ] Update required scipp version in `conda` buildconfig.
