### ISSUE TITLE
Partial solution to memory (and performance) issues when mapping many input bins to many output bins

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#2741]
Consider
```python
from numpy.random import default_rng

import scipp as sc

rng = default_rng(seed=1234)

N0 = 300000
N1 = 10000
table = sc.data.table_xyz(int(1e8))
da = table.bin(x=N0)
param = sc.array(dims=['x'], values=rng.random(da.shape))
da.coords['param'] = param
edges = sc.linspace('param', 0.0, 1.0, num=N1+1)
```
This is about 3 GByte of binned data. We have a param for each bin (not for each event) and want to bin/group by that (a typically neutron-scattering application of this is to map pixels to their scattering angle).

Now run (or better not, decrease N0 and/or N1 first):
```python
%%time
base = da.bin(param=edges)
base
```
This takes about 1 minute, but more problematically it uses more than 70 Gbyte of temporary memory. The reason is the same as discussed in #1846. This is one more case where to current optimized branch is not taken.

When we do not need to consider every event on its own, there is a simple solution to this. Here is a working Python solution:

```python
%%time
#TODO masks
output_bin_lut = sc.DataArray(sc.arange('param', len(edges)-1), coords={'param':edges})
func = sc.lookup(output_bin_lut)
output_bin = func(param)

sizes = sc.DataArray(da.bins.size().data, coords={'output_bin':output_bin, 'input_bin':sc.arange('x', len(da))})
sizes_sort_out = sc.sort(sizes, 'output_bin')

# subbin sizes
out_end = sc.cumsum(sizes_sort_out.data)
out_begin = out_end - sizes_sort_out.data

sizes_sort_out.coords['out_begin'] = out_begin
sizes_sort_out.coords['out_end'] = out_end
sizes_sort_in = sc.sort(sizes_sort_out, 'input_bin')

out = sc.bins(
    data=sc.empty_like(da.bins.constituents['data']),
    dim=da.bins.constituents['dim'],
    begin=sizes_sort_in.coords['out_begin'],
    end=sizes_sort_in.coords['out_end'],
)

%%time
out[...] = da.data

%%time
#TODO would drop empty bins, give groups explicitly!
out_sizes = sizes_sort_out.groupby('output_bin').sum('x').rename(output_bin='param')
out_end = sc.cumsum(out_sizes.data)
out_begin = out_end - out_sizes.data
out = sc.bins(
    data=out.bins.constituents['data'],
    dim=out.bins.constituents['dim'],
    begin=out_begin,
    end=out_end,
)
out = sc.DataArray(out, coords={'param':edges})
out
```
This takes less than 2 seconds (and uses a relatively negligible amount of memory).

To do:
- [ ] Should probably move this to C++
- [ ] Figure out how to safely detect cases when this can be used. This can also be supported with multiple (erased) input dims and multiple binning dims.
- [ ] Handle masks (may come for free if done in C++ inside existing binning alg.
- [ ] Figure out if this can be combined with binning by other event coords. We can either use a 2-stage approach (simpler) ok make use of the existing mechanism (harder to understand).

**Comment by SimonHeybrock** [comment]
Addressing a simpler problem first: `da.bins.concat(dim)`. I'll try to go with a Python-only solution.
