### ISSUE TITLE
Steps for `attrs` removal

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#3166]
See #3145.

Main steps (may be incomplete, needs decision on timeline):

- [x] Deprecate `DataArray.attrs` see #3227 
- [x] Deprecation period? -> 24.12.0
- [x] Update Scipp docs
- [ ] How can we avoid backsliding?
- [x] Deprecate `scippneutron.load`, add `scippneutron.load_with_mantid` loading as `DataGroup` see scipp/scippneutron#444
- [x] Change `plopp` to only look at `coords`, not `attrs`. see scipp/plopp#241
- [x] Removing `attrs` before we have a workflow system implemented would mean duplicate refactoring effort for certain data-reduction workflows
- [x] Refactor `scippuncertainties`
- [ ] Document scope of Scipp.
- [x] Consider how to handle loading of legacy Scipp HDF5 files. Should we load old files that have attrs as DataGroup? -> mainly used internally, ignore the problem

Alignment-flag refactor related:

- [x] Change `scippnexus` slicing behavior.

**Comment by nvaytet** [comment]
We also need to remember to update our docs which talk about `attrs`, fx [here](https://scipp.github.io/user-guide/data-structures/data-structures.html#id1)
