### ISSUE TITLE
Umbrella: Code consolidation

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#58]
Over the past months `dataset` has been evolved from a basic prototype into something like a tech demo. To go beyond that we need to take a step back and consolidate the current code base.

This issue provides an overview of what needs to be done and is meant as a point to gather any large or small issues or annoyances encountered during development.

1. Code structure
   - [x] Move into different parent organization, and rename?
   - [x] Need to split into independent sub-modules, potentially in different repositories.
     - [x] Python module as separate repo? (done for now)
     - [x] Can we extract our neutron-specific unit system such that the core library does not depend on it?
   - Sub-namespaces (`data`, `neutron::units`, `neutron::tof`, ...?)?
1. Testing & build system
   - [x] Massively increase unit testing. In particular a fair amount of code written early in the design process has poor test completeness.
   - [ ] Add memcheck to Travis.
   - [ ] Add address-sanitizer to Travis. Also read https://kristerw.blogspot.com/2018/06/useful-gcc-address-sanitizer-checks-not.html. (see https://github.com/scipp/scipp/issues/202)
   - [x] `clang-format` as part of CI?
   - [x] `cmake-format`. (doing that locally)
   - [x] `flake8` (`autopep3`?)
   - [x] Enable more compiler warnings (see https://github.com/lefticus/cppbestpractices/blob/master/02-Use_the_Tools_Available.md#compilers).
   - [x] `ctest` integration for running `gtest` test and Python tests (done, but slow)
   - [ ] `coverage` coverage metrics (and possible minimum coverage failure thresholds?). Something like [this](https://github.com/eddyxu/cpp-coveralls) might be suitable. Some instructions for configuring with cmake/travis [here](http://david-grs.github.io/cpp-clang-travis-cmake-gtest-coveralls-appveyor/)
   - [ ] Windows CI : better to introduce earlier maybe via [appveyor](https://www.appveyor.com/)?
1. Operations for `Variable`
   - [x] As more operations are added we have to ensure to make this a convenient process. In particular we will want to support operations with mixed argument types, which is tricky right now (would need multiple-dynamic dispatch). (done, see `transform`)
     - One potential solution to is would be to use `std::variant` in `Variable` to hold the data. Unknown data could be supported by a fallback alternative in the variant (a base class pointer). We can then use `std::visit` to implement arbitrary operations, including the option to pass arbitrary lambdas.
   - [x] These changes should make the implementation of mixed-precision (or in general mixed-type) operations more convenient.
1. Operations for `Dataset` (done, see `Dataset` rewrite)
   - [x] Need refactoring for a unified way of defining the behavior of variable-groups under operations. The most common example is values with variances, which require different operations for error propagation. There is a half-done sketch of a way to to this in branch https://github.com/mantidproject/dataset/tree/tag-group. See also #160 (may not be necessary any more in this generic way if https://github.com/scipp/scipp/pull/200 works as expected)
1. View classes
   - [ ] We need to converge to a solution for transforming views, i.e., a common way to read data that is computed based on one or more other variables. The main examples for this are: Bin edges, standard-deviation, spectrum-geometry such as positions (based on detector-geometry, combined via detector-grouping). Currently the only way is to use `zipMD` which is very inconvenient and has no operator support. We want something that can be directly multiplied/added with a `Variable`, and has proper support for units. (*postpone*)
   - [ ] Along the same lines, we may consider introducing a typed `Variable`, which might use, e.g., `xtensor` to store arbitrary expressions. It is however not clear how much overlap of this solution there is with an approach discussed above, using `std::variant` to support applying arbitrary operators to items in variables. (*postpone*)
   - [ ] Which `zip` views to we want/need? (*postpone*)
1. Documentation
   - [ ] Doxygen everywhere.
   - [ ] Sphinx for Python (how can we use it it combination with pybind11?).
   - [x] `readthedocs.io` (done, need content)
   - [ ] Define documentation rules for functions, etc., such as behavior under exceptions, ...
1. Other
   - [ ] `Dataset::dimensions()` should not return `Dimensions`, which implies an ordering.
   - [x] Adding new tags and new data types requires touching too many places, in particular for Python exports, need to improve this. (obsolete)
   - [ ] Refactor/redesign API to allow for in-place operation, avoiding copies where possible. Both in C++ and Python.
   - [ ] Attempt to give unified exception guarantees, e.g., that data is never corrupted, and usually preserved. Right now, operations on a dataset may fail half-way through and leave data in a semi-processed state.
   - [x] Apart from potential built-ins, tags and dimension labels should not be prescribed by the core library. It should be possible to provide a different set at compile time. Ideally we would like a core set that can be extended, in a way that makes extensions in different libraries compatible.
   - [ ] Work on compile-times for code using the API.
   - [ ] For pybind11, we had to enable PIC (see https://github.com/pybind/pybind11/issues/466). Read https://eli.thegreenplace.net/2011/11/03/position-independent-code-pic-in-shared-libraries/ and understand the overhead?

**Comment by SimonHeybrock** [comment]
Many things have been addressed, others will be addressed in separate issues. Closing.
