### ISSUE TITLE
Scipp Developer Meeting: Agenda and minutes

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#808]
# Discussion items

### Conceptual and logical issues with `Dataset`, `DataArray`, and sparse data

- [x] Per-item masks?
     - [x] *Make masks per-item (DataArray).*
     - [x] *Remove masks property from dataset*
     - [ ] *Better, or worse?: Make masks part of `Variable` -> inception is bad*
- [x] Alignment promise of `Dataset` vs. sparse data. Issues with `DataArray`, which cannot have dense coord together with sparse. *solved by new event data API*
- [x] `out` args for data array, rules and concepts for handling/propagating coords, labels, masks, attrs.
     ```python
     sc.sin(var, out=var) # would fail if changing unit was not allowed
     sc.transpose(var, out=var)
     
     # DataArray
     sc.sin(a, out=a) # in-place modification of data, coords irrelevant
     sc.sin(a, out=b) # check coords? change coords? add coords? yes!
     b = sc.sin(a) # returns DataArray
     b2 = sc.sin(a, out=c) # returns DataProxy
     b == b2 # requirement
     # =>
     # - removes existing coord, masks, attrs
     # - adds coords, masks, attrs
     # - modifies data
     # - changes dimension labels of data
     
     # neutron.convert
     b1 = sc.neutron.convert(a)
     b2 = sc.neutron.convert(a, out=a)
     b1 == b2 # requirement
     ```
     *casting result to output precision should be allowed (as numpy, useful for sum in higher precision than input, see #493)*
- [x] We can `sum` data along `Dim.Spectrum` when in unit `Tof`. We have no mechanism for preventing this. Can there / should there be one?
     *No, too restrictive, but often other coords prevent bads things from propagating:*
     ```python
     focussed = sc.sum(data, 'spectrum')
     dspacing = sc.neutron.convert(focussed, 'tof', 'd-spacing')
     ```
     *`neutron.convert` fails since `sum` drops the `position` coord.*
- [x] Remove dimension labels in favor of strings #936. *yes*
     - [x] Try using string directly in `class Dimensions` (simplest refactor). Check performance of `groupby` with many small groups. Check performane of interactive slicing with slider in plot.
- [x] Rename "sparse data" -> "event data"? *yes*
- [x] New API for event data #949.
- [x] New API for virtual coords to enable a more natural way of working with pixel-based data, replacing 1-D list of points in space. Similar to #949, to be included in same solution. Related to unit conversion and handling of coordinates and attributes.

#### Unresolved

- [ ] Sparse data without data, should we just store 0-D data and rely on broadcasts. Can working with sparse data be made less cumbersome? *postpone until after event API refactor*
- [ ] Views and proxies #454 *very low priority / nice to have for now*

Connected set of issues around attributes and meta data. Discussions did not result in better solutions:
- [ ] Attributes are now separate for dataset and its items (not mapping to elements). See issues around unit conversion and attribute duplication.
- [x] Attribute propagation rules.
- [ ] #856 categories of (meta) data, and actions taking in operations.

### General Discussions 
- [x] Can we or should we move to c++20, what would this bring us? *not available yet*
- [x] Development wiki or otherwise *include in `git` as part of overall project documentation*
- [x] How to use alongside Mantid?
     - [x] *fix conda packages for Mantid*
     - [ ] *better documentation for cases when conda cannot be used*
- [x] C++ documentation *see #955*
     - [ ] *also include information on design choices, etc.*
     - [ ] *include "table of contents" for code*
     - [x] *rename (not just C++!)*
     - [x] *add "How to..." section, specific to developing with internals*
- [x] Ways of working, developer discussion
     - [ ] *Add roadmap*

### CI Related
- [x] How to properly track incremental changes yielding slower build times? At moment larger effort to go back and fix. *should be solved by switch to Azure pipelines*
- [x] Should we more explicitly select compiler versions for example - always latest stable? Should we periodically check and update available packages/images for compilers on CI? *try to use latest stable*
- [x] Windows CI does not include pre-build sanitiser/static-analysis checks, which is potentially wasteful. Should we duplicate on the windows side?  *should be solved by switch to Azure pipelines*
- [x] Move to a single, well configured pipeline on a single service rather than the less than ideal collection of free tier products we currently use? *should be solved by switch to Azure pipelines*

### Testing
- [x] More systematic and maintainable testing #513
     - [x] Extract lambda implementing element-wise operations from implementation.
     - [x] Test lambda separately (applied to `Unit` as well as elements of different types).
     - [x] Test of, e.g., `Variable::sqrt` can then rely on correctness of underlying components, and just need to test that components are combined in the correct way:
          - `Unit::sqrt`
          - `ValueAndVariance::sqrt`
          - `transform` and `transform_in_place`
          - `element_wise::sqrt`
- [x] Alternative unit testing for trivial Python exports (just test existence and signatures) #986
     - [x] *yes, implement mechanism*
     - [x] *but ensure it is really only used for trivial bindings*

### Planning
- [x] Review/update [risks](https://confluence.esss.lu.se/display/DAM/scipp+planning)
- [x] Review/update high-level milestone/release plan [here](https://confluence.esss.lu.se/display/DAM/scipp+planning)
- [x] Would be useful to review where we are regarding DREAM and the scipp no-MPI objective
     - *Do not need MPI (performance results available soon)*
     - *Unsolved challenge is file loading*
     - *Dask is more flexible and can probably help to overcome most remaining issues.*
- [x] ~~Tackling ESTIA, approximately when to start, how to organise with Arthur G~~ Second Instrument, what would our preference be.
     - [ ] *Add basic workflows for LoKI and ODIN (as examples/tutorials in the docs?).*
- [x] Far future ideas - How to handle workbench like requests. *Say NO! -> focus on specific widgets (in Jupyter) or at some point potentially technique-specific interfaces*

# Agenda

## Day 1 (Tuesday 2020-02-11)

- CR05: ground floor, [R112][r112]

|Time         |Location           |Item|
|-------------|-------------------|----|
|10:00 - 12:00|CR05               |Conceptual and logical issues - part 1|
|12:00 - 13:00|[R1][r1]/[R22][r22]|Lunch|
|13:00 - 14:30|CR05               |Conceptual and logical issues - part 2|
|15:00 - 15:30|[R1][r1]           |Break|
|15:30 - 16:30|CR05               |Conceptual and logical issues - part 3|

## Day 2 (Wednesday 2020-02-12)

- CR20: fourth floor, [R106][r106]
- CR21: first floor, [R1][r1]

|Time         |Location           |Item|
|-------------|-------------------|----|
|09:00 - 10:00|CR20               |Planning|
|10:00 - 10:30|?                  |Break|
|10:30 - 12:00|CR20               |General discussion - part 1|
|12:00 - 13:00|[R1][r1]/[R22][r22]|Lunch|
|13:00 - 14:30|CR21               |ALC xarray meeting|
|14:30 - 15:00|[R1][r1]           |Break|
|15:00 - 16:30|CR20               |General discussion - part 2|

## Day 3 (Thursday 2020-02-13)

- CR22: first floor, [R1][r1]
- CR25: first floor, [R1][r1]

|Time         |Location           |Item|
|-------------|-------------------|----|
|09:00 - 10:00|CR22               |Testing|
|10:00 - 10:30|[R1][r1]           |Break|
|10:30 - 12:30|CR22               |No specific topic - continue earlier discussions?|
|12:30 - 13:30|[R1][r1]/[R22][r22]|Lunch|
|13:30 - 14:45|CR22               |CI Issues|
|14:45 - 15:00|[R1][r1]           |Break|
|15:00 - 16:30|CR25               |Presentation to PACE|

[r1]: https://www.openstreetmap.org/relation/2725112
[r22]: https://www.openstreetmap.org/way/200338765
[r106]: https://www.openstreetmap.org/way/739041537
[r112]: https://www.openstreetmap.org/way/739044217

**Comment by DanNixon** [comment]
Locations:
- Tuesday 11th: CR05, Ground Floor, R112 (new visitors centre)
- Wednesday 12th: CR20, 4th Floor, R106
- Thursday 13th: CR22, 1st Floor, R1
- Friday 14th: CR22, 1st Floor, R1

**Comment by nvaytet** [comment]
From the list of discussion issues, we could also add:
- More systematic and maintainable testing #513 
- Views and proxies #454
