### ISSUE TITLE
Remove dimension labels in favor of strings

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#936]
### Implementation steps

On the Python side "refactoring" implies:
- change any use of the old `Dim` labels to a string.
- change any use of `labels` to use `coords` instead.

To do:

- [x] @SimonHeybrock Refactor `scipp-core`:
     - [x] ~Try using string directly in class Dimensions (simplest refactor).~ 2x slowdown in groupby, even without string comparisons everywhere.
     - [x] Check performance of groupby with many small groups.
     - [ ] Check performane of interactive slicing with slider in plot.
     - [x] Use more complex refactor based on map from strings to integer IDs, if above option is unsuccessful.
- [x] Refactor Python bindings
- [x] Refactor Python part of `scipp.neutron` @SimonHeybrock 
- [x] Refactor Python tests. -> @nvaytet 
- [x] Refactor `scipp.plot` -> @nvaytet
- [x] Refactor other visualization. @SimonHeybrock 
- [x] Refactor documentation. -> @nvaytet 
- [x] Refactor benchmarks.

Note that step one is a prerequisite, but most of the others can run in parallel.
 
### Overview

This is about:

1. Dimension labels such as `Dim.X` or `Dim.Tof`.
2. The resulting split between coords and labels.

### Pros of current approach

- Dimension labels are just a small integer and thus cheap to copy and compare, enabling high performance, e.g., in operations with many small slices.
- Labels are hard coded and aid in avoiding typos.

### Neutral?

- Split between coords and labels is on the one hand nice because it adds a clear distinction between dimension-coordinates and non-dimension coordinates. xarray does so only by marking them with a star in `__repr__`. On the other hand this is probably confusing for some and also adds code overhead in some places.

### Cons of the current approach

- Hard coded labels implies that adding new dimension requires recompilation.
- Additional training and documentation effort.
- Slightly more complex and harder-to-maintain code.
- As we are beginning to add more complex functionality, examples where a switch from a string-label to a dimension is required. In the current approach this mapping must thus be manually specified. Example:
  - `groupby`:
    ```python
    # special `combine` parameter required:
    grouped = sc.groupby(data, group='z', combine=Dim.Z).mean(Dim.X)
    # with string-based labels we can use:
    grouped = sc.groupby(data, group='z').mean('x')
- Harder to implemented interoperability with xarray.
- Noisier interface?

### Technical details

- For dimension labels (not for the coord keys), we probably still want to avoid storing strings internally (for performance reasons). I would propose to maintain a mapping from string to and ID. Strings would be used on the user-facing interfaces, IDs keep internals efficient. By using pre-defined labels for all the common cases the mapping can be keep efficient and free of locking even for multi-threaded applications, except for special additional labels that are introduced.

**Comment by nvaytet** [comment]
I agree that it's a good idea to keep the dimension IDs internally for performance. Although it might be confusing to someone if they suddently see that using `d.coords["X"]` is 10x faster than `d.coords['x']`. Is there a way to automatically generate new integer IDs for any string input?

**Comment by SimonHeybrock** [comment]
I would be a bit surpised if any non-extreme use of the API would make the performance differences visible. I am not 100% clear about the implementation, but the translation `string -> int` would happen at the interface level. The difference is that for known strings the translation is fixed, whereas for new unknown strings we need to update the map for the translation (unless we just use plain hashing without collision handling). The update of the map would include a lock (since sonner or later we need multi-threading support). The lock would probably never be entered for previously used keys, only when new keys are added.

**Comment by OwenArnold** [comment]
Given we are still in pre-stable release phase, its a good time to consider this. I think it would be useful to know from the `xarray` community whether they have additional pros for their approach, and what they see as the cons (does that agree with our list).

I like the hard-coded labels. One nice feature is that the access to dimensions is also consistent , no special strings, ubiquitous between scripts etc. but this limits us to compile-time changes. I believe compile times themselves should not be a concern with the way that Dims are implemented?
