### ISSUE TITLE
Improvements for developer documentation

### ISSUE THREAD

**Issue by SimonHeybrock** [scipp/scipp#955]
For the developer documentation (to be included on readthedocs):
- [x] Rename (not just "C++")
- [x] Include "table of contents" for code -> partially addressed by splitting modules and choosing better file names
- [x] Add "How to..." section, similar to user-ordientied [How to...](https://scipp.readthedocs.io/en/latest/user-guide/how_to.html), but specific to developing with internals (mainly but not exclusively C++) (added page and single entry in https://github.com/scipp/scipp/pull/987)
- [x] Include information on design and conceptual choices -> partially addressed in #1098.
- [x] Add more detailed roadmap. -> see #1044 
- [x] Instantiation of `Variable` with custom type.
- [x] `transform` and `transform_in_place` usage. See #1098

**Comment by OwenArnold** [comment]
I think everyone should be contributing to this as scipp development moves along, new concepts etc.

**Comment by SimonHeybrock** [comment]
All subtasks have now been addressed, at least to some extent, or are covered in other issues. Closing.
